### ISSUE TITLE
[1.1] Error while instantiating a mod of type Fluffy_BirdsAndBees.Controller

### ISSUE THREAD

**Issue by BaalEvan** [FluffierThanThou/BirdsAndBees#26]
**Describe the bug**  
Error after initialization

**Expected behavior**  
No error 

**Steps to reproduce**  
Enable BirdsAndBees

**Other mods**  
There is also warning about duplicate blueprint in blueprint mod (PSD)

**Output log**  
Copy from console:
https://pastebin.com/fSt1fQgK

**Environment**  
 - OS: W10
 - 64 bits 

**Game**
 - 64 bits
 - Steam
 - Version: 1.1.2558

**Comment by FluffierThanThou** [comment]
Thanks for the report!

any chance you could post a hugslib output_log link (press `Ctrl+F12`)? That includes some information on e.g. the version of Harmony used, which is probably very relevant.

**Comment by kdryja** [comment]
Seeing same issue here.
See the logs from `Ctrl+F12`: https://gist.github.com/cbba21645db274d32b0c8d0add1faca7

**Comment by FluffierThanThou** [comment]
@kdryja that particular set of errors should have been fixed with the latest release.

**Comment by kdryja** [comment]
Indeed seems to be fixed for me now.
Thanks for the quick fix and your amazing mods!
