### ISSUE TITLE
V0.16.0.4 Doesn't seem to be save compatable

### ISSUE THREAD

**Issue by Goldfish300** [FluffierThanThou/BirdsAndBees#7]
As title suggests, none of my saves load. All produce the same error. Reverting to the previous version of Birds and Bees allows the save to be loaded again. Log, mod config and a save are provided in the dropbox link.

https://www.dropbox.com/sh/g1dgq1rdcqczpsa/AAAgBWQ-pn0C0f7E1TXh7XtFa?dl=0

From looking at the source code changes, the error log and the comment made on the steam workshop (about conjoined people), I would guess that the save files have references to these 'conjoined' body parts, which are destroyed when the new version forces the cache to clear.
However I have very little knowledge of how these things work in Rimworld and exactly what data is stored in the save file, so take with a pinch of salt.

**Comment by FluffierThanThou** [comment]
You're exactly right on all counts, including the solution. The damage is done here, there's not much I can do right now other than ask people to only update after starting a new game.

**Comment by FluffierThanThou** [comment]
While leaving this issue up for a while could solve as a pointer for others experiencing the same issues, I doubt anyone is still around with a save game of this specific version, and with A17 coming up I'm clearing out old issues.
