### ISSUE TITLE
Previously working save now breaks: Dangerous detour

### ISSUE THREAD

**Issue by monikersupreme** [FluffierThanThou/BirdsAndBees#9]
I can start a new game but my previously working save (as of last night) now breaks on load. 

[output_log.txt](https://github.com/FluffierThanThou/BirdsAndBees/files/773245/output_log.txt)

[Stone Valley 63.zip](https://github.com/FluffierThanThou/BirdsAndBees/files/773247/Stone.Valley.63.zip)

[ModsConfig.zip](https://github.com/FluffierThanThou/BirdsAndBees/files/773249/ModsConfig.zip)

Side note, I'm interested in getting into modding this game myself so if I can assist at all let me know.

**Comment by FluffierThanThou** [comment]
argh. yep, I see the issue. Thanks for the info!

**Comment by FluffierThanThou** [comment]
oh for the record, this is caused by the WorkTab, not the Birds and the Bees. I've fixed the problem, just testing it a bit before I put it out there

**Comment by FluffierThanThou** [comment]
fix for work tab is out

**Comment by FluffierThanThou** [comment]
oh, by the way, this was a simple fix so I didn't really need any help. 

But if you ever need some more advice on modding stuff, feel free to ask me on the forums. There's also a few good beginners guides and stuff on there.

**Comment by monikersupreme** [comment]
Thanks much! Yeah, I've been looking through a few of the guides, I'm sure there will be questions to come.
